vtk_module(SignedTensor
  DEPENDS
    vtkCommonExecutionModel
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkCommonTransforms
  TEST_DEPENDS
    vtkFiltersCore
    vtkFiltersModeling
    vtkIOLegacy
    vtkImagingCore
    vtkInteractionStyle
    vtkRenderingAnnotation
    vtkRenderingLabel
    vtkRendering${VTK_RENDERING_BACKEND}
    vtkRenderingCore
  )
